travis:
  secure:
    BINSTAR_TOKEN: ReZq39jlogymGzLmzwh+C7eCdOGDLAGWw2+TCQs1a3rDxxOp9ocVZTc7Jhizq9DcgHkra7rkqBklQ21pG1KnLJ0kc+9m2eXGrxSBsyQKZRk/VZmlpEnX19n3pKFtWs1VRiZSXWi49/4mw9Fw19jqyZw/EV748Fo9uD8d2+pExDpeQGJxCzlSuqNZqwhSlA6sWWvk7rNstWaEX2hsCe4uQWNyaFEH0vhmz0YME0HU3dHWkNOgXRNN1SIEn2eTc7PFR8TVNmak9Rc4Masmn41dwrfrECHD18tyKd6DjSHtT+DZBOFeceTuvzKvI7KNv4Y+9FXnJ+4/HHM45PJPXYBqKkApvgqnlLAOs3L8a5gbeSsf9g6FZmRhKsT8PD2iHwVBjJsw8nZ5tkhUynmpB+lqtQoYGpgqa9IkSxBA4n/Kn5+io8Uw4e20VaByqwxFLNwlbOLAGoZNSoe2LJzEFpg+/XzNzwFCrZoS8wS67IqK9+DYckLtSTCTxHd36K+t3Uki0QqLkauPbTLxpgDhJfWqHpDbsHxQuGPB+ejqFUV/N8PrhJYFcZO0HNSVgMOiZNCd5F2o1BPpwIc9I6f1fvq2kBlcrjkfthbiT3lnOgDKbuAYUlSFQEpAYMYXpN44nb9MpvSoKsTUJMFE1SIQOhP30I26ujKH26D7nTTmQ+95j5Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
